### ISSUE TITLE
关于楼主说的UI组件

### ISSUE THREAD

**Issue by liuyang1106** [Nealyang/study-redux#2]
我觉得楼主描述的UI组件不应该加上这一行，
const {counter,increment,decrement,incrementIfOdd,incrementAsync} = this.props;
因为UI组件不应该像容器一样通过props去获取store传过来的API什么的，UI组件应该直接写成函数式组件，接受容器组件传过来的参数应该更好，这样的UI组件和容器组件不就区分的十分清楚吗？

**Comment by Nealyang** [comment]
UI组件的确不能够从store中拿数据，这是刚开始学习的时候写的demo，你可以看下我别的仓库demo，上面的使用，基本是比较规范的。多谢指正！
